name: homelab-dashboard

networks:
  homelab-dashboard:
    driver: bridge

services:
  homelab-dashboard:
    environment:
      - HostProc=/host/proc
      - HostSys=/host/sys
      - HostEtc=/host/etc
      - APP_DATABASE_URI=file:data.db?cache=shared&mode=rwc
      - APP_SERVER_PORT=8080
      - APP_SERVER_LOG_LEVEL=debug
      - APP_SERVER_SECRET_KEY=test_secret
      - APP_SERVER_UPDATE_FREQUENCY=2000
      - APP_SERVER_ADMIN_AUTH_USERNAME=admin
      - APP_SERVER_ADMIN_AUTH_PASSWORD=123
    hostname: homelab-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /proc 
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys 
        target: /host/sys
        read_only: true
      - type: bind
        source: /etc 
        target: /host/etc
        read_only: true
      - type: bind
        source: /var/run/docker.sock 
        target: /var/run/docker.sock
        read_only: true
    networks:
      - homelab-dashboard
    privileged: true
